package com.socialsentiment.entity;


import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Represents the stock sentiment data associated with a specific stock symbol.
 *
 * The `StockSentiment` entity is mapped to the "stock_sentiment" table in the database.
 */
@Entity
@Table(name = "stock_sentiment")
public class StockSentiment {

    /**
     * The unique identifier for the {@code StockSentiment} entity.
     *
     * This field is automatically generated by the persistence provider
     * using the {@code GenerationType.IDENTITY} strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Represents the stock's ticker symbol associated with this sentiment data.
     *
     * This variable stores the unique identifier for a specific stock
     * used in sentiment analysis.
     */
    private String symbol;

    /**
     * Stores the message content related to a stock sentiment entity.
     *
     * This field is a CLOB used for storing online user comment data related to a stock
     * sentiment analysis.
     */
    @Lob
    private String message;

    /**
     * Represents the sentiment classification of a stock-related message.
     *
     * The `sentiment` variable indicates the sentiment associated with the stock message.
     */
    private String sentiment;

    /**
     * Represents the analysis method used to generate the sentiment data.
     *
     * This field is mapped to the "analysis_method" column in the "stock_sentiment" table
     * and is used to differentiate and filter stock sentiment data based on the applied analysis approach.
     */
    @Column(name = "analysis_method")
    private String analysisMethod;

    /**
     * Represents the unique identifier for a stock sentiment message.
     *
     * This variable is a {@code Long} type and can be utilized to correlate or reference stock sentiment
     * messages across different entities or external systems.
     */
    @Column(name = "message_id", unique = true)
    private Long messageId;

    /**
     * Represents the timestamp when this entity was created.
     *
     * The {@code createdAt} field captures the date and time
     * when a specific instance of the {@code StockSentiment} entity
     * was initialized or persisted.
     */
    private LocalDateTime createdAt;

    // Getters and setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getSymbol() { return symbol; }
    public void setSymbol(String symbol) { this.symbol = symbol; }

    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }

    public String getSentiment() { return sentiment; }
    public void setSentiment(String sentiment) { this.sentiment = sentiment; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public Long getMessageId() { return messageId; }
    public void setMessageId(Long messageId) { this.messageId = messageId; }


    public String getAnalysisMethod() { return analysisMethod; }
    public void setAnalysisMethod(String analysisMethod) { this.analysisMethod = analysisMethod; }

}
