package com.socialsentiment.entity;


import jakarta.persistence.*;

import java.time.LocalDateTime;

/**
 * Represents a tracked stock symbol, including its related metadata.
 * This entity is mapped to the "tracked_symbols" table in the database.
 *
 **/
@Entity
@Table(name = "tracked_symbols")
public class TrackedSymbol {
    /**
     * Represents the unique identifier for a {@code TrackedSymbol} entity.
     *
     * This field is is the primary key and is automatically generated by
     * the database during the insertion of a new record.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Represents the stock symbol being tracked.
     *
     * This field stores the unique identifier for a stock or financial asset,
     * typically used in stock exchanges or trading platforms.
     */
    private String symbol;
    /**
     * Represents the name associated with the tracked stock symbol.
     *
     * This field provides additional context or description for the tracked symbol.
     */
    private String name;

    /**
     * Represents the timestamp when the {@code TrackedSymbol} entity was created.
     *
     * This field is automatically populated with the current timestamp. It is mapped
     * to the "created_at" column in the database and is immutable after being set.
     */
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;


    // Automatically set createdAt before saving
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    // Getters and Setters
    public Long getId() { return id; }

    public String getSymbol() { return symbol; }
    public void setSymbol(String symbol) { this.symbol = symbol; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public LocalDateTime getCreatedAt() { return createdAt; }


}